import {Component} from 'react';

class FacesDb extends Component {
    static get() {
        return (
            [
                {face: '( ͡° ͜ʖ ͡°)', name: 'hmmm'},
                {face: '¯\\_(ツ)_/¯', name: 'what'},
                {face: '( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)', name: 'many hmmm'},
                {face: '(▀̿Ĺ̯▀̿ ̿)', name: 'turn down for what'},
                {face: 'ʕ•ᴥ•ʔ', name: 'bear'},
                {face: '(ง ͠° ͟ل͜ ͡°)ง', name: 'fight'},
                {face: '༼ つ ◕_◕ ༽つ', name: 'cute amoeba'},
                {face: 'ಠ_ಠ', name: 'eyes'},
                {face: '(づ｡◕‿‿◕｡)づ', name: 'cute pong'},
                {face: '[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]', name: 'dollar'},
                {face: '(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ ✧ﾟ･: *ヽ(◕ヮ◕ヽ)', name: 'sparkling'},
                {face: '┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴', name: 'hmm wall'},
                {face: '(ง\'̀-\'́)ง', name: 'fight 2'},
                {face: '(ಥ﹏ಥ)', name: 'cry'},
                {face: '﴾͡๏̯͡๏﴿ O\'RLY?', name: 'rly'},
                {face: '(ᵔᴥᵔ)', name: 'bear 2'},
                {face: '(づ￣ ³￣)づ', name: 'kiss'},
                {face: 'ಠ╭╮ಠ', name: 'not bad'},
                {face: '(｡◕‿‿◕｡)', name: 'cute'},
                {face: '¢‿¢',  name: ' '},
                {face: '©¿© o',  name: ' '},
                {face: 'ª{•̃̾_•̃̾}ª',  name: ' '},
                {face: '¬_¬',  name: ' '},
                {face: '¯＼(º_o)/¯',  name: ' '},
                {face: '¯\(º o)/¯',  name: ' '},
                {face: '¯\_(⊙︿⊙)_/¯',  name: ' '},
                {face: '¯\_(ツ)_/¯',  name: ' '},
                {face: '°ω°',  name: ' '},
                {face: '°Д°',  name: ' '},
                {face: '°‿‿°',  name: ' '},
                {face: '°ﺑ°',  name: ' '},
                {face: '´ ▽ ` )ﾉ',  name: ' '},
                {face: '¿ⓧ_ⓧﮌ',  name: ' '},
                {face: 'Ò,ó',  name: ' '},
                {face: 'ó‿ó',  name: ' '},
                {face: 'ô⌐ô',  name: ' '},
                {face: 'ôヮô',  name: ' '},
                {face: 'ŎםŎ',  name: ' '},
                {face: 'ŏﺡó',  name: ' '},
                {face: 'ʕ•̫͡•ʔ',  name: ' '},
                {face: 'ʕ•ᴥ•ʔ',  name: ' '},
                {face: 'ʘ‿ʘ',  name: ' '},
                {face: '˚•_•˚',  name: ' '},
                {face: '˚⌇˚',  name: ' '},
                {face: '˚▱˚',  name: ' '},
                {face: '̿ ̿̿\'̿\'\̵͇̿̿\=(•̪●)=/̵͇̿̿/\'̿̿ ̿ ̿ ̿',  name: ' '},
                {face: '͡° ͜ʖ﻿ ͡°',  name: ' '},
                {face: 'Σ ◕ ◡ ◕',  name: ' '},
                {face: 'Σ (ﾟДﾟ;）', name: 'surprised'},
                {face: 'Σ(ﾟДﾟ；≡；ﾟдﾟ)', name: 'confusion'},
                {face: 'Σ(ﾟДﾟ )',  name: ' '},
                {face: 'Σ(||ﾟДﾟ)', name: 'scary'},
                {face: 'Φ,Φ',  name: ' '},
                {face: 'δﺡό',  name: ' '},
                {face: 'σ_σ',  name: ' '},
                {face: 'д_д',  name: ' '},
                {face: 'ф_ф',  name: ' '},
                {face: 'щ（ﾟДﾟщ）', name: 'Dear god why?'},
                {face: 'щ(ಠ益ಠщ)',  name: ' '},
                {face: 'щ(ಥДಥщ)',  name: ' '},
                {face: 'Ծ_Ծ',  name: ' '},
                {face: 'أ‿أ',  name: ' '},
                {face: 'ب_ب',  name: ' '},
                {face: 'ح˚௰˚づ',  name: ' '},
                {face: 'ح˚ᆺ˚ว',  name: ' '},
                {face: 'حᇂﮌᇂ)',  name: ' '},
                {face: '٩๏̯͡๏۶',  name: ' '},
                {face: '٩๏̯͡๏)۶',  name: ' '},
                {face: '٩◔̯◔۶',  name: ' '},
                {face: '٩(×̯×)۶',  name: ' '},
                {face: '٩(̾●̮̮̃̾•̃̾)۶',  name: ' '},
                {face: '٩(͡๏̯͡๏)۶',  name: ' '},
                {face: '٩(͡๏̯ ͡๏)۶',  name: ' '},
                {face: '٩(ಥ_ಥ)۶',  name: ' '},
                {face: '٩(•̮̮̃•̃)۶',  name: ' '},
                {face: '٩(●̮̮̃•̃)۶',  name: ' '},
                {face: '٩(●̮̮̃●̃)۶',  name: ' '},
                {face: '٩(｡͡•‿•｡)۶',  name: ' '},
                {face: '٩(-̮̮̃•̃)۶',  name: ' '},
                {face: '٩(-̮̮̃-̃)۶',  name: ' '},
                {face: '۞_۞',  name: ' '},
                {face: '۞_۟۞',  name: ' '},
                {face: '۹ↁﮌↁ',  name: ' '},
                {face: '۹⌤_⌤۹',  name: ' '},
                {face: '॓_॔',  name: ' '},
                {face: '१✌◡✌५',  name: ' '},
                {face: '१|˚–˚|५',  name: ' '},
                {face: 'ਉ_ਉ',  name: ' '},
                {face: 'ଘ_ଘ',  name: ' '},
                {face: 'இ_இ',  name: ' '},
                {face: 'ఠ_ఠ',  name: ' '},
                {face: 'రృర',  name: ' '},
                {face: 'ಠ¿ಠi',  name: ' '},
                {face: 'ಠ‿ಠ',  name: ' '},
                {face: 'ಠ⌣ಠ',  name: ' '},
                {face: 'ಠ╭╮ಠ',  name: ' '},
                {face: 'ಠ▃ಠ',  name: ' '},
                {face: 'ಠ◡ಠ',  name: ' '},
                {face: 'ಠ益ಠ',  name: ' '},
                {face: 'ಠ益ಠ',  name: ' '},
                {face: 'ಠ︵ಠ凸',  name: ' '},
                {face: 'ಠ , ಥ',  name: ' '},
                {face: 'ಠ.ಠ',  name: ' '},
                {face: 'ಠoಠ',  name: ' '},
                {face: 'ಠ_ృ',  name: ' '},
                {face: 'ಠ_ಠ',  name: ' '},
                {face: 'ಠ_๏',  name: ' '},
                {face: 'ಠ~ಠ',  name: ' '},
                {face: 'ಡ_ಡ',  name: ' '},
                {face: 'ತಎತ',  name: ' '},
                {face: 'ತ_ತ',  name: ' '},
                {face: 'ಥдಥ',  name: ' '},
                {face: 'ಥ‿ಥ',  name: ' '},
                {face: 'ಥ⌣ಥ',  name: ' '},
                {face: 'ಥ◡ಥ',  name: ' '},
                {face: 'ಥ﹏ಥ',  name: ' '},
                {face: 'ಥ_ಥ', name: 'So... Beautiful'},
                {face: 'ಭ_ಭ',  name: ' '},
                {face: 'ರ_ರ',  name: ' '},
                {face: 'ಸ , ໖',  name: ' '},
                {face: 'ಸ_ಸ',  name: ' '},
                {face: 'ക_ക',  name: ' '},
                {face: 'อ้_อ้',  name: ' '},
                {face: 'อ_อ',  name: ' '},
                {face: 'โ๏௰๏ใ ื',  name: ' '},
                {face: '๏̯͡๏﴿',  name: ' '},
                {face: '๏̯͡๏',  name: ' '},
                {face: '๏̯͡๏﴿',  name: ' '},
                {face: '๏[-ิิ_•ิ]๏',  name: ' '},
                {face: '๏_๏',  name: ' '},
                {face: '໖_໖',  name: ' '},
                {face: '༺‿༻',  name: ' '},
                {face: 'ლ(´ڡ`ლ)',  name: ' '},
                {face: 'ლ(́◉◞౪◟◉‵ლ)',  name: ' '},
                {face: 'ლ(ಠ益ಠლ)  y u no guy', name: '  y u no guy'},
                {face: 'ლ(╹◡╹ლ)',  name: ' '},
                {face: 'ლ(◉◞౪◟◉‵ლ)',  name: ' '},
                {face: 'ლ,ᔑ•ﺪ͟͠•ᔐ.ლ',  name: ' '},
                {face: 'ᄽὁȍ ̪ őὀᄿ',  name: ' '},
                {face: 'ᕕ( ᐛ )ᕗ',  name: ' '},
                {face: 'ᕙ(⇀‸↼‶)ᕗ',  name: ' '},
                {face: 'ᕦ(ò_óˇ)ᕤ',  name: ' '},
                {face: 'ᶘ ᵒᴥᵒᶅ    ← baby seal',  name: ' '},
                {face: '‘︿’',  name: ' '},
                {face: '•▱•',  name: ' '},
                {face: '•✞_✞•',  name: ' '},
                {face: '•ﺑ•',  name: ' '},
                {face: '•(⌚_⌚)•',  name: ' '},
                {face: '•_•)',  name: ' '},
                {face: '‷̗ↂ凸ↂ‴̖',  name: ' '},
                {face: '‹•.•›',  name: ' '},
                {face: '‹› ‹(•¿•)› ‹›',  name: ' '},
                {face: '‹(ᵒᴥᵒ­­­­­)›﻿',  name: ' '},
                {face: '‹(•¿•)›',  name: ' '},
                {face: 'ↁ_ↁ',  name: ' '},
                {face: '⇎_⇎',  name: ' '},
                {face: '∩(︶▽︶)∩',  name: ' '},
                {face: '∩( ・ω・)∩', name: 'happy dog'},
                {face: '≖‿≖',  name: ' '},
                {face: '≧ヮ≦',  name: ' '},
                {face: '⊂•⊃_⊂•⊃',  name: ' '},
                {face: '⊂⌒~⊃｡Д｡)⊃',  name: ' '},
                {face: '⊂(◉‿◉)つ',  name: ' '},
                {face: '⊂(ﾟДﾟ,,⊂⌒｀つ',  name: ' '},
                {face: '⊙ω⊙',  name: ' '},
                {face: '⊙▂⊙',  name: ' '},
                {face: '⊙▃⊙',  name: ' '},
                {face: '⊙△⊙',  name: ' '},
                {face: '⊙︿⊙',  name: ' '},
                {face: '⊙﹏⊙',  name: ' '},
                {face: '⊙０⊙',  name: ' '},
                {face: '⊛ठ̯⊛',  name: ' '},
                {face: '⋋ō_ō`',  name: ' '},
                {face: '━━━ヽ(ヽ(ﾟヽ(ﾟ∀ヽ(ﾟ∀ﾟヽ(ﾟ∀ﾟ)ﾉﾟ∀ﾟ)ﾉ∀ﾟ)ﾉﾟ)ﾉ)ﾉ━━━',  name: ' '},
                {face: '┌∩┐(◕_◕)┌∩┐',  name: ' '},
                {face: '┌( ಠ_ಠ)┘',  name: ' '},
                {face: '┌( ಥ_ಥ)┘',  name: ' '},
                {face: '╚(•⌂•)╝',  name: ' '},
                {face: '╭╮╭╮☜{•̃̾_•̃̾}☞╭╮╭╮',  name: ' '},
                {face: '╭✬⌢✬╮',  name: ' '},
                {face: '╮(─▽─)╭',  name: ' '},
                {face: '╯‵Д′)╯彡┻━┻', name: 'angry guy flipping a table'},
                {face: '╰☆╮',  name: ' '},
                {face: '□_□',  name: ' '},
                {face: '►_◄',  name: ' '},
                {face: '◃┆◉◡◉┆▷',  name: ' '},
                {face: '◉△◉',  name: ' '},
                {face: '◉︵◉',  name: ' '},
                {face: '◉_◉',  name: ' '},
                {face: '○_○',  name: ' '},
                {face: '●¿●\ ~',  name: ' '},
                {face: '●_●',  name: ' '},
                {face: '◔̯◔',  name: ' '},
                {face: '◔ᴗ◔',  name: ' '},
                {face: '◔ ⌣ ◔',  name: ' '},
                {face: '◔_◔',  name: ' '},
                {face: '◕ω◕',  name: ' '},
                {face: '◕‿◕',  name: ' '},
                {face: '◕◡◕',  name: ' '},
                {face: '◕ ◡ ◕',  name: ' '},
                {face: '◖♪_♪|◗',  name: ' '},
                {face: '◖|◔◡◉|◗', name: 'Huuuuur'},
                {face: '◘_◘',  name: ' '},
                {face: '◙‿◙',  name: ' '},
                {face: '◜㍕◝',  name: ' '},
                {face: '◪_◪',  name: ' '},
                {face: '◮_◮',  name: ' '},
                {face: '☁ ☝ˆ~ˆ☂',  name: ' '},
                {face: '☆¸☆',  name: ' '},
                {face: '☉‿⊙',  name: ' '},
                {face: '☉_☉',  name: ' '},
                {face: '☐_☐',  name: ' '},
                {face: '☜ق❂Ⴢ❂ق☞',  name: ' '},
                {face: '☜(⌒▽⌒)☞',  name: ' '},
                {face: '☜(ﾟヮﾟ☜)',  name: ' '},
                {face: '☜-(ΘLΘ)-☞',  name: ' '},
                {face: '☝☞✌',  name: ' '},
                {face: '☮▁▂▃▄☾ ♛ ◡ ♛ ☽▄▃▂▁☮',  name: ' '},
                {face: '☹_☹',  name: ' '},
                {face: '☻_☻',  name: ' '},
                {face: '☼.☼',  name: ' '},
                {face: '☾˙❀‿❀˙☽',  name: ' '},
                {face: '♀ح♀ヾ',  name: ' '},
                {face: '♥‿♥',  name: ' '},
                {face: '♥╣[-_-]╠♥',  name: ' '},
                {face: '♥╭╮♥',  name: ' '},
                {face: '♥◡♥',  name: ' '},
                {face: '✌♫♪˙❤‿❤˙♫♪✌',  name: ' '},
                {face: '✌.ʕʘ‿ʘʔ.✌',  name: ' '},
                {face: '✌.|•͡˘‿•͡˘|.✌',  name: ' '},
                {face: '✖‿✖',  name: ' '},
                {face: '✖_✖',  name: ' '},
                {face: '❐‿❑',  name: ' '},
                {face: '⨀_⨀',  name: ' '},
                {face: '⨀_Ꙩ',  name: ' '},
                {face: '⨂_⨂',  name: ' '},
                {face: '〆(・∀・＠)',  name: ' '},
                {face: '《〠_〠》',  name: ' '},
                {face: '【•】_【•】',  name: ' '},
                {face: '〠_〠',  name: ' '},
                {face: '〴⋋_⋌〵',  name: ' '},
                {face: 'のヮの',  name: ' '},
                {face: 'ニガー? ━━━━━━(ﾟ∀ﾟ)━━━━━━ ニガー?',  name: ' '},
                {face: 'ペ㍕˚\\',  name: ' '},
                {face: 'ヽ(´ｰ｀ )ﾉ',  name: ' '},
                {face: 'ヽ(๏∀๏ )ﾉ',  name: ' '},
                {face: 'ヽ(｀Д´)ﾉ',  name: ' '},
                {face: 'ヽ(ｏ`皿′ｏ)ﾉ',  name: ' '},
                {face: 'ヽ(`Д´)ﾉ',  name: ' '},
                {face: 'ㅎ_ㅎ',  name: ' '},
                {face: '乂◜◬◝乂',  name: ' '},
                {face: '凸ಠ益ಠ)凸',  name: ' '},
                {face: '句_句',  name: ' '},
                {face: 'Ꙩ⌵Ꙩ',  name: ' '},
                {face: 'Ꙩ_Ꙩ',  name: ' '},
                {face: 'ꙩ_ꙩ',  name: ' '},
                {face: 'Ꙫ_Ꙫ',  name: ' '},
                {face: 'ꙫ_ꙫ',  name: ' '},
                {face: 'ꙮ_ꙮ',  name: ' '},
                {face: '흫_흫',  name: ' '},
                {face: '句_句',  name: ' '},
                {face: '﴾͡๏̯͡๏﴿ O\'RLY?', name: 'O\'RLY?'},
                {face: '﻿¯\(ºдಠ)/¯',  name: ' '},
                {face: '（·×·）',  name: ' '},
                {face: '（⌒Д⌒）',  name: ' '},
                {face: '（╹ェ╹）',  name: ' '},
                {face: '（♯・∀・）⊃',  name: ' '},
                {face: '（　´∀｀）☆',  name: ' '},
                {face: '（　´∀｀）',  name: ' '},
                {face: '（゜Д゜）',  name: ' '},
                {face: '（・∀・）', name: '"well" or "good"'},
                {face: '（・Ａ・）', name: '"bad" or "not good"'},
                {face: '（ﾟ∀ﾟ）',  name: ' '},
                {face: '（￣へ￣）',  name: ' '},
                {face: '（ ´☣///_ゝ///☣｀）',  name: ' '},
                {face: '（ つ Д ｀）',  name: ' '},
                {face: '＿☆（ ´_⊃｀）☆＿',  name: ' '},
                {face: '｡◕‿‿◕｡',  name: ' '},
                {face: '｡◕ ‿ ◕｡',  name: ' '},
                {face: '!⑈ˆ~ˆ!⑈',  name: ' '},
                {face: '!(｀･ω･｡)',  name: ' '},
                {face: '(¬‿¬)',  name: ' '},
                {face: '(¬▂¬)',  name: ' '},
                {face: '(¬_¬)',  name: ' '},
                {face: '(°ℇ °)',  name: ' '},
                {face: '(°∀°)',  name: ' '},
                {face: '(´ω｀)',  name: ' '},
                {face: '(´◉◞౪◟◉)',  name: ' '},
                {face: '(´ヘ｀;)',  name: ' '},
                {face: '(´・ω・｀)',  name: ' '},
                {face: '(´ー｀)',  name: ' '},
                {face: '(ʘ‿ʘ)',  name: ' '},
                {face: '(ʘ_ʘ)',  name: ' '},
                {face: '(˚இ˚)',  name: ' '},
                {face: '(͡๏̯͡๏)',  name: ' '},
                {face: '(ΘεΘ;)',  name: ' '},
                {face: '(ι´Д｀)ﾉ',  name: ' '},
                {face: '(Ծ‸ Ծ)',  name: ' '},
                {face: '(॓_॔)',  name: ' '},
                {face: '(० ्०)',  name: ' '},
                {face: '(ு८ு_ .:)',  name: ' '},
                {face: '(ಠ‾ಠ﻿)',  name: ' '},
                {face: '(ಠ‿ʘ)',  name: ' '},
                {face: '(ಠ‿ಠ)',  name: ' '},
                {face: '(ಠ⌣ಠ)',  name: ' '},
                {face: '(ಠ益ಠ ╬)',  name: ' '},
                {face: '(ಠ益ಠ)',  name: ' '},
                {face: '(ಠ_ృ)',  name: ' '},
                {face: '(ಠ_ಠ)',  name: ' '},
                {face: '(ಥ﹏ಥ)',  name: ' '},
                {face: '(ಥ_ಥ)',  name: ' '},
                {face: '(๏̯͡๏ )',  name: ' '},
                {face: '(ღˇ◡ˇ)~♥',  name: ' '},
                {face: '(ღ˘⌣˘ღ) ♫･*:.｡. .｡.:*･', name: 'happy with music'},
                {face: '(ღ˘⌣˘ღ) - no thx',  name: ' '},
                {face: '(ᵔᴥᵔ)',  name: ' '},
                {face: '(•ω•)',  name: ' '},
                {face: '(•‿•)',  name: ' '},
                {face: '(•⊙ω⊙•)',  name: ' '},
                {face: '(• ε •)',  name: ' '},
                {face: '(∩▂∩)',  name: ' '},
                {face: '(∩︵∩)',  name: ' '},
                {face: '(∪ ◡ ∪)',  name: ' '},
                {face: '(≧ω≦)',  name: ' '},
                {face: '(≧◡≦)',  name: ' '},
                {face: '(≧ロ≦)',  name: ' '},
                {face: '(⊙ヮ⊙)',  name: ' '},
                {face: '(⊙_◎)',  name: ' '},
                {face: '(⋋▂⋌)',  name: ' '},
                {face: '(⌐■_■)',  name: ' '},
                {face: '(─‿‿─)',  name: ' '},
                {face: '(┛◉Д◉)┛┻━┻',  name: ' '},
                {face: '(╥_╥)',  name: ' '},
                {face: '(╬ಠ益ಠ)',  name: ' '},
                {face: '(╬◣д◢)',  name: ' '},
                {face: '(╬ ಠ益ಠ)',  name: ' '},
                {face: '(╯°□°）╯︵ ┻━┻', name: 'table flip'},
                {face: '(╯ಊ╰)',  name: ' '},
                {face: '(╯◕_◕)╯',  name: ' '},
                {face: '(╯︵╰,)',  name: ' '},
                {face: '(╯3╰)',  name: ' '},
                {face: '(╯_╰)',  name: ' '},
                {face: '(╹◡╹)凸',  name: ' '},
                {face: '(▰˘◡˘▰)',  name: ' '},
                {face: '(●´ω｀●)',  name: ' '},
                {face: '(●´∀｀●)', name: 'relieved happy'},
                {face: '(◑‿◐)',  name: ' '},
                {face: '(◑◡◑)',  name: ' '},
                {face: '(◕‿◕✿)', name: 'cute happy'},
                {face: '(◕‿◕)',  name: ' '},
                {face: '(◕‿-)',  name: ' '},
                {face: '(◕︵◕)',  name: ' '},
                {face: '(◕ ^ ◕)',  name: ' '},
                {face: '(◕_◕)',  name: ' '},
                {face: '(◜௰◝)',  name: ' '},
                {face: '(◡‿◡✿)',  name: ' '},
                {face: '(◣_◢)',  name: ' '},
                {face: '(☞ﾟ∀ﾟ)☞',  name: ' '},
                {face: '(☞ﾟヮﾟ)☞',  name: ' '},
                {face: '(☞ﾟ ∀ﾟ )☞',  name: ' '},
                {face: '(☼◡☼)',  name: ' '},
                {face: '(☼_☼)',  name: ' '},
                {face: '(✌ﾟ∀ﾟ)☞',  name: ' '},
                {face: '(✖╭╮✖)',  name: ' '},
                {face: '(✪㉨✪)',  name: ' '},
                {face: '(✿◠‿◠)',  name: ' '},
                {face: '(✿ ♥‿♥)',  name: ' '},
                {face: '(　・∀・)',  name: ' '},
                {face: '(　･ัω･ั)？',  name: ' '},
                {face: '(　ﾟ∀ﾟ)o彡゜えーりんえーりん!!',  name: ' '},
                {face: '(。・_・。)',  name: ' '},
                {face: '(つд｀)',  name: ' '},
                {face: '(づ｡◕‿‿◕｡)づ',  name: ' '},
                {face: '(ノಠ益ಠ)ノ彡┻━┻',  name: 'table flip'},
                {face: '(ノ ◑‿◑)ノ',  name: ' '},
                {face: '(ノ_・。)',  name: ' '},
                {face: '(・∀・ )',  name: ' '},
                {face: '(屮ﾟДﾟ)屮', name: '"Come on" or "Come here"'},
                {face: '(︶ω︶)',  name: ' '},
                {face: '(︶︹︺)',  name: ' '},
                {face: '(ﺧ益ﺨ)',  name: ' '},
                {face: '(；一_一)',  name: ' '},
                {face: '(｀・ω・´)”', name: 'innocent happy'},
                {face: '(｡◕‿‿◕｡)',  name: ' '},
                {face: '(｡◕‿◕｡)',  name: ' '},
                {face: '(｡◕ ‿ ◕｡)',  name: ' '},
                {face: '(｡♥‿♥｡)',  name: ' '},
                {face: '(｡･ω..･)っ',  name: ' '},
                {face: '(･ｪ-)',  name: ' '},
                {face: '(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧',  name: ' '},
                {face: '(ﾟДﾟ)', name: '"heh?" or "what are you saying?" or "surprised"'},
                {face: '(ﾟДﾟ)y─┛~~', name: 'smoking'},
                {face: '(ﾟ∀ﾟ)',  name: ' '},
                {face: '(ﾟヮﾟ)',  name: ' '},
                {face: '(￣□￣)',  name: ' '},
                {face: '(￣。￣)',  name: ' '},
                {face: '(￣ー￣)',  name: ' '},
                {face: '(￣(エ)￣)',  name: ' '},
                {face: '( °٢° )',  name: ' '},
                {face: '( ´_ゝ｀)',  name: ' '},
                {face: '( ͡° ͜ʖ ͡°)',  name: ' '},
                {face: '( ͡~ ͜ʖ ͡°)',  name: ' '},
                {face: '( ಠ◡ಠ )',  name: ' '},
                {face: '( •_•)>⌐■-■',  name: ' '},
                {face: '( 　ﾟ,_ゝﾟ)',  name: ' '},
                {face: '( ･ิз･ิ)',  name: ' '},
                {face: '( ﾟдﾟ)､', name: 'vomits saliva'},
                {face: '( ^▽^)σ)~O~)',  name: ' '},
                {face: '((((゜д゜;))))',  name: ' '},
                {face: '(*´д｀*)',  name: ' '},
                {face: '(*..Д｀)',  name: ' '},
                {face: '(*..д｀*)',  name: ' '},
                {face: '(*~▽~)',  name: ' '},
                {face: '(-’๏_๏’-)',  name: ' '},
                {face: '(-＿- )ノ',  name: ' '},
                {face: '(/◔ ◡ ◔)/',  name: ' '},
                {face: '(///_ಥ)',  name: ' '},
                {face: '(;´Д`)',  name: ' '},
                {face: '(=ω=;)',  name: ' '},
                {face: '(=゜ω゜)',  name: ' '},
                {face: '(>\'o\')> ♥ <(\'o\'<)',  name: ' '},
                {face: '(n˘v˘•)¬',  name: ' '},
                {face: '(o´ω｀o)',  name: ' '},
                {face: '(V)(°,,°)(V)',  name: ' '},
                {face: '(\/) (°,,°) (\/)', name: 'WOOPwoopwowop!'},
                {face: '(^▽^)',  name: ' '},
                {face: '(`･ω･´)', name: 'Pedobear?'},
                {face: '(~￣▽￣)~',  name: ' '},
                {face: '/╲/\\╭ºoꍘoº╮/\\╱\\',  name: ' '},
                {face: '<【☯】‿【☯】>',  name: ' '},
                {face: '=(ﾟдﾟ)ｳ',  name: ' '},
                {face: '@_@',  name: ' '},
                {face: 'd(*⌒▽⌒*)b',  name: ' '},
                {face: 'o(≧∀≦)o',  name: ' '},
                {face: 'o(≧o≦)o',  name: ' '},
                {face: 'q(❂‿❂)p',  name: ' '},
                {face: 'y=ｰ( ﾟдﾟ)･∵.', name: 'shot my head'},
                {face: '\\˚ㄥ˚\\',  name: ' '},
                {face: '\\ᇂ_ᇂ\\',  name: ' '},
                {face: '\(ಠ ὡ ಠ )/',  name: ' '},
                {face: '\(◕ ◡ ◕\)',  name: ' '},
                {face: '^̮^',  name: ' '},
                {face: '^ㅂ^',  name: ' '},
                {face: '_(͡๏̯͡๏)_',  name: ' '},
                {face: '{´◕ ◡ ◕｀}',  name: ' '},
                {face: '{ಠ_ಠ}__,,|,',  name: ' '},
                {face: '{◕ ◡ ◕}',  name: ' '},
                {face: 'Ƹ̵̡Ӝ̵̨̄Ʒ', name : 'butterfly'},
                {face: '̜ ̳ ̳ ̳ ̳ ͙ ڪ ', name : '  '},
                {face: '̴ı̴̴̡̡̡ ̡͌l̡̡̡ ̡͌l̡*̡̡ ̴̡ı̴̴̡ ̡̡͡|̲̲̲͡͡͡ ̲▫̲͡ ̲̲̲͡͡π̲̲͡͡ ̲̲͡▫̲̲͡͡ ̲|̡̡̡ ̡ ̴̡ı̴̡̡ ̡͌l̡̡̡̡.', name : '  '},
                {face: '▄︻̷̿┻̿═━一', name : '  '},
                {face: '♡+♡=❤²', name : '  '},
                {face: '✄---------❤', name : '  '},
                {face: '¦¬)', name : '  '},
                {face: '|-)', name : '  '},
                {face: '¦3', name : '  '},
                {face: '〓D', name : '  '},
                {face: '/:€', name : 'Myth Busted!'},
                {face: ':⌉', name : '  '},
                {face: '=⌉', name : '  '},
                {face: 'Ӭ', name : '  '},
                {face: 'ӭ', name : '  '},
                {face: 'ۃ', name : '  '},
                {face: '⌤', name : ' '},
                {face: '⍢', name : '  '},
                {face: '⍣', name : '  '},
                {face: '⍤', name : '  '},
                {face: '⍥', name : 'om nom nom'},
                {face: '⍨', name : '  '},
                {face: '⍩', name : '  '},
                {face: '☃', name : '  '},
                {face: '☹', name : '  '},
                {face: '☺', name : '  '},
                {face: '☻', name : '  '},
                {face: '♾', name : '  '},
                {face: '⚍', name : '  '},
                {face: '〠', name : 'smile in hat'},
                {face: 'シ', name : '  '},
                {face: 'ツ', name : '  '},
                {face: '㋡', name : '  '},
                {face: 'ﺕ', name : '  '},
            ]
        );
    }

    static getRandom () {
            let faces = this.get();
            let currentIndex = faces.length, temporaryValue, randomIndex;

            while (0 !== currentIndex) {
                randomIndex = Math.floor(Math.random() * currentIndex);
                currentIndex -= 1;

                temporaryValue = faces[currentIndex];
                faces[currentIndex] = faces[randomIndex];
                faces[randomIndex] = temporaryValue;
            }

            return faces;
    }
}

export default FacesDb;